name: Build and push protocol buffer definitions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: install golang
        run: sudo snap install go --classic
      - name: install buf
        # Substitute BIN for your bin directory.
        # Substitute VERSION for the current released version.
        # Substitute BINARY_NAME for "buf", "protoc-gen-buf-breaking", or "protoc-gen-buf-lint".
        run: BIN="/usr/local/bin" && VERSION="1.0.0-rc6" && BINARY_NAME="buf" && curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/${BINARY_NAME}-$(uname -s)-$(uname -m)" -o "${BIN}/${BINARY_NAME}" && chmod +x "${BIN}/${BINARY_NAME}"
      - name: Compile the protocol buffer files to golang
        env:
          TOKEN_NAME: ${{ secrets.TOKEN_NAME }}
          TOKEN_VALUE: ${{ secrets.TOKEN_VALUE }}
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
          GO_CODE_PATH: "github.com/byteintellect/protos_go"
        run: PATH=$PATH:/home/ubuntu/go/bin make SOURCE_CODE_PATH=$HOME/go_proto_files ORIGIN_PATH=https://${TOKEN_NAME}:${TOKEN_VALUE}@github.com/byteintellect/protos_go.git build_and_push_go
