name: Build and push protocol buffer definitions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: install golang
        run: sudo snap install go --classic
      - name: Compile the protocol buffer files to golang
        env:
          TOKEN_NAME: ${{ secrets.TOKEN_NAME }}
          TOKEN_VALUE: ${{ secrets.TOKEN_VALUE }}
        run: make ORIGIN_PATH=https://${TOKEN_NAME}:${TOKEN_VALUE}@github.com/byteintellect/protos_go.git build_and_push_go